- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create EC2 key pair
      ec2_key:
        name: dcos_admin
        state: present
        region: "{{ aws_region }}"
        key_material: "{{ item }}"
      with_file: dcos_public_key

    - name: Create Mesosphere DCOS cluster
      cloudformation:
        stack_name: dcos
        state: present
        region: "{{ aws_region }}"
        template_url: "https://s3.amazonaws.com/downloads.mesosphere.io/dcos/{{ dcos_channel }}/cloudformation/{{ dcos_master_setup }}.cloudformation.json"
        template_parameters:
          AcceptEULA: "Yes"
          AdminLocation: 0.0.0.0/0
          KeyName: dcos_admin
          PublicSlaveInstanceCount: 1
          SlaveInstanceCount: 5
      register: dcos_stack

    - set_fact:
        dcos_url: "http://{{ dcos_stack.stack_outputs.DnsAddress }}"

    - name: Create tmp folder
      file: path=tmp/.dcos state=directory mode=0755

    - name: Generate DCOS CLI configuration
      template:
        src: templates/dcos.toml.j2
        dest: tmp/.dcos/dcos.toml

    - debug: msg="Open DCOS web interface at {{ dcos_url }}"
